// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxWpe_uwOZG1PWVXOhTUjf7deZ3EQEiYo',
    appId: '1:481882455062:web:4c6b17d703877df0eb8937',
    messagingSenderId: '481882455062',
    projectId: 'e-commerce-app-7e8d1',
    authDomain: 'e-commerce-app-7e8d1.firebaseapp.com',
    storageBucket: 'e-commerce-app-7e8d1.appspot.com',
    measurementId: 'G-TDKB6NYN5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7US7J17tLbVxAStOjT8zYg2d2U8jV1eo',
    appId: '1:481882455062:android:8d0621101ba84c5deb8937',
    messagingSenderId: '481882455062',
    projectId: 'e-commerce-app-7e8d1',
    storageBucket: 'e-commerce-app-7e8d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj98NHEv4r1YNFRcwp2lD9s-vdIjB9Yt0',
    appId: '1:481882455062:ios:a05588188b5af856eb8937',
    messagingSenderId: '481882455062',
    projectId: 'e-commerce-app-7e8d1',
    storageBucket: 'e-commerce-app-7e8d1.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj98NHEv4r1YNFRcwp2lD9s-vdIjB9Yt0',
    appId: '1:481882455062:ios:a05588188b5af856eb8937',
    messagingSenderId: '481882455062',
    projectId: 'e-commerce-app-7e8d1',
    storageBucket: 'e-commerce-app-7e8d1.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxWpe_uwOZG1PWVXOhTUjf7deZ3EQEiYo',
    appId: '1:481882455062:web:8564e667424bb3efeb8937',
    messagingSenderId: '481882455062',
    projectId: 'e-commerce-app-7e8d1',
    authDomain: 'e-commerce-app-7e8d1.firebaseapp.com',
    storageBucket: 'e-commerce-app-7e8d1.appspot.com',
    measurementId: 'G-Z1LEMT9M8R',
  );
}
